### PR TITLE
Types of crime and how common they are during each hour

### PR DESCRIPTION
**Pull request by kamikasky**

### CODE REVIEW

**Comment by hcorrada** [comment]
I can't run this entry. Object 'HOUR' is not defined

**Comment by kamikasky** [comment]
Yes, the comments state that 'to see the distribution for a specific hour, replace HOUR with a number 1-24'

**Comment by hcorrada** [comment]
Please turn in something I can reproduce. I.e., replace HOUR with a value and conclude the analysis. Also, please remember to pull the latest version of the Rmd file as described in the homework.

**Comment by kamikasky** [comment]
Sure, I've updated it now.

**Comment by hcorrada** [comment]
Please merge curent version and commit again

**Comment by kamikasky** [comment]
Alright, I merged and then committed (after having to fix some conflicts). If it still isn't what you requested, please provide some steps I can follow to accomplish the task.

**Pull request merged**
