### PR TITLE
Anna Petrone submission

### PR DESCRIPTION
**Pull request by annapetrone**
Here is my submissions for part 1. I used an external data set that I downloaded from the Baltimore neighborhood indicators alliance http://bniajfi.org/mapping-resources/

### CODE REVIEW

**Comment by hcorrada** [comment]
Please add the dataset to the repository using

``` shell
git add <filename>
git commit -m "adding dataset"
```

You can update the pull request then.

Cheers,
Hector

**Comment by annapetrone** [comment]
Added my data files in a zip file

**Comment by annapetrone** [comment]
Can you see my new commit with the data?

**Comment by annapetrone** [comment]
Thanks for your comments - I should have thought of those in the first place.

**Comment by hcorrada** [comment]
Very nice!

**Pull request merged**
